const AuthActionTypes = {
  LOGIN: 'LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_ERROR: 'LOGIN_ERROR',
  LOGOUT: 'LOGOUT',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_ERROR: 'LOGOUT_ERROR',
  CHECK_USER_SESSION: 'CHECK_USER_SESSION',
  CHECK_USER_SESSION_FINISHED: 'CHECK_USER_SESSION_FINISHED',
};

export default AuthActionTypes;
