const IPCActionTypes = {
  FETCH_HISTORY: 'FETCH_HISTORY',
  FETCH_HISTORY_SUCCESS: 'FETCH_HISTORY_SUCCESS',
  FETCH_HISTORY_ERROR: 'FETCH_HISTORY_ERROR',
  TOGGLE_THEME: 'TOGGLE_THEME',
};

export default IPCActionTypes;
